{application,check_checker,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"check_checker"},
              {modules,['Elixir.CheckChecker',
                        'Elixir.CheckChecker.ChessPiece',
                        'Elixir.CheckChecker.CoordinateConversions',
                        'Elixir.CheckChecker.Helpers']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
